In [1]:
# Import pandas library
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv("Placement.csv")

In [ ]:
# Display first five rows
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [8]:
# Check missing values in each column
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [9]:
# Fill missing salary values with 0 because students who are not placed do not have a salary.

df["salary"] = df["salary"].fillna(0)

In [10]:
df.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [3]:
df = df.drop_duplicates()

In [4]:
print(df.shape)

(215, 15)

In [5]:
df["gender"] = df["gender"].str.strip().str.upper()

df["ssc_b"] = df["ssc_b"].str.strip().str.title()

df["hsc_b"] = df["hsc_b"].str.strip().str.title()

df["hsc_s"] = df["hsc_s"].str.strip().str.title()

df["degree_t"] = df["degree_t"].str.strip().str.title()

df["workex"] = df["workex"].str.strip().str.title()

df["specialisation"] = df["specialisation"].str.strip().str.title()

df["status"] = df["status"].str.strip().str.title()

In [6]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [11]:
df["salary"] = df["salary"].astype(int)

In [12]:
df.rename(columns={
    "ssc_p":"ssc_percentage",
    "hsc_p":"hsc_percentage",
    "degree_p":"degree_percentage",
    "etest_p":"employability_test_percentage",
    "mba_p":"mba_percentage"
}, inplace=True)

In [13]:
df["average_percentage"] = (
    df["ssc_percentage"] +
    df["hsc_percentage"] +
    df["degree_percentage"] +
    df["mba_percentage"]
) / 4

In [14]:
df.to_csv("cleaned_dataset.csv", index=False)